version: '3'
services:
  #####################################
  # APPLICATION SERVICE ENVIRONMENT
  #####################################
  app:
    build: .
    restart: always
    healthcheck:
      start_period: 60s
      timeout: 120s
      interval: 30s
      test: echo ${USER}
    ports:
      - 3000:3000
    env_file: .env
    depends_on:
      - redis
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - node_networks
  ##############################
  # REDIS SERVICE ENVIRONMENT
  ##############################
  redis:
    image: redis:7-alpine
    restart: always
    healthcheck:
      start_period: 60s
      timeout: 120s
      interval: 30s
      test: echo ${USER}
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis
    networks:
      - node_networks
# #############################
# # VOLUME PERSISTENT DATA
# #############################
volumes:
  redis:
    #############################
    # NETWORKS SHARING GROUP
    #############################
networks:
  node_networks:
